// This file was automatically generated by the NPoco T4 Template
// Do not make changes dNewstly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `FountainConPoco`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.\SQLEXPRESS; User ID=sa; password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `True`

using System;
using System.Collections.Generic;
using System.Linq;
using NPoco;

namespace FountainContext.Data.Models
{
	public partial class FountainDb : Database
	{
		public FountainDb() : base("FountainConPoco")
		{
			CommonConstruct();
		}

		public FountainDb(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		public virtual void CommonConstruct()
		{
		    Factory = new DefaultFactory();
		}
		
		public interface IFactory
		{
			FountainDb GetInstance();
		    void BeginTransaction(FountainDb database);
		    void CompleteTransaction(FountainDb database);
		}

        public class DefaultFactory : IFactory
        {
            [ThreadStatic]
            static Stack<FountainDb> _stack = new Stack<FountainDb>();

            public FountainDb GetInstance()
            {
               
			    if (_stack == null)
                { return new  FountainDb(); }
                else { 
					return _stack.Count > 0 ? _stack.Peek() : new FountainDb();
                }
			   
			    
            }

            public void BeginTransaction(FountainDb database)
            {

			 if (_stack == null)
				 {
				  _stack = new  Stack<FountainDb>();
				 }
                _stack.Push(database);
            }

            public void CompleteTransaction(FountainDb database)
            {
			 if (_stack == null)
				 {
				  _stack = new Stack <FountainDb>();
				 }
                _stack.Pop();
            }
        }
		
		public static IFactory Factory { get; set; }

        public static FountainDb GetInstance()
        {
		 if (Factory == null)
                return new FountainDb();
			return Factory.GetInstance();
        }

		protected override void OnBeginTransaction()
		{
            Factory.BeginTransaction(this);
		}

        protected override void OnCompleteTransaction()
		{
            Factory.CompleteTransaction(this);
		}
		public class Record<T> where T:new()
		{
			public bool IsNew(Database db) { return db.IsNew(this); }
			public object Insert(Database db) { return db.Insert(this); }  
			
			public int Update(Database db, IEnumerable<string> columns) { return db.Update(this, columns); }
			public static int Update(Database db, string sql, params object[] args) { return db.Update<T>(sql, args); }
			public static int Update(Database db, Sql sql) { return db.Update<T>(sql); }
			public int Delete(Database db) { return db.Delete(this); }
			public static int Delete(Database db, string sql, params object[] args) { return db.Delete<T>(sql, args); }
			public static int Delete(Database db, Sql sql) { return db.Delete<T>(sql); }
			public static int Delete(Database db, object primaryKey) { return db.Delete<T>(primaryKey); }
			public static bool Exists(Database db, object primaryKey) { return db.Exists<T>(primaryKey); }
			public static T SingleOrDefault(Database db, string sql, params object[] args) { return db.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Database db, Sql sql) { return db.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(Database db, string sql, params object[] args) { return db.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Database db, Sql sql) { return db.FirstOrDefault<T>(sql); }
			public static T Single(Database db, string sql, params object[] args) { return db.Single<T>(sql, args); }
			public static T Single(Database db, Sql sql) { return db.Single<T>(sql); }
			public static T First(Database db, string sql, params object[] args) { return db.First<T>(sql, args); }
			public static T First(Database db, Sql sql) { return db.First<T>(sql); }
			public static List<T> Fetch(Database db, string sql, params object[] args) { return db.Fetch<T>(sql, args); }
			public static List<T> Fetch(Database db, Sql sql) { return db.Fetch<T>(sql); }
			public static List<T> Fetch(Database db, long page, long itemsPerPage, string sql, params object[] args) { return db.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(Database db, long page, long itemsPerPage, Sql sql) { return db.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(Database db, long skip, long take, string sql, params object[] args) { return db.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(Database db, long skip, long take, Sql sql) { return db.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(Database db, long page, long itemsPerPage, string sql, params object[] args) { return db.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(Database db, long page, long itemsPerPage, Sql sql) { return db.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(Database db, string sql, params object[] args) { return db.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Database db, Sql sql) { return db.Query<T>(sql); }			
			
			protected HashSet<string> Tracker = new HashSet<string>();
			private void OnLoaded() { Tracker.Clear(); }
			protected void Track(string c) { if (!Tracker.Contains(c)) Tracker.Add(c); }

			public int Update(Database db) 
			{ 
				if (Tracker.Count == 0)
					return db.Update(this); 

				var retv = db.Update(this, Tracker.ToArray());
				Tracker.Clear();
				return retv;
			}
			public void Save(Database db) 
			{
                if (this.IsNew(db))
					Insert(db);
				else
					Update(db);
			}		
		}	
	}		
		[TableName("dbo.Pure_Tracking")]
		[PrimaryKey("Tid")]
		[ExplicitColumns]
		public partial class PureTracking : FountainDb.Record<PureTracking>  
		{
	        [Column] public int Tid 
			{ 
				get { return _Tid; }
				set { _Tid = value; Track("Tid"); }
			}
			int _Tid;
			[Column("UserName")] public string Username 
			{ 
				get { return _Username; }
				set { _Username = value; Track("UserName"); }
			}
			string _Username;
			[Column("SessionId")] public string Sessionid 
			{ 
				get { return _Sessionid; }
				set { _Sessionid = value; Track("SessionId"); }
			}
			string _Sessionid;
			[Column("SystemIp")] public string Systemip 
			{ 
				get { return _Systemip; }
				set { _Systemip = value; Track("SystemIp"); }
			}
			string _Systemip;
			[Column("SystemName")] public string Systemname 
			{ 
				get { return _Systemname; }
				set { _Systemname = value; Track("SystemName"); }
			}
			string _Systemname;
			[Column("LoginDate")] public DateTime? Logindate 
			{ 
				get { return _Logindate; }
				set { _Logindate = value; Track("LoginDate"); }
			}
			DateTime? _Logindate;
		
			public static IEnumerable<PureTracking> Query(Database db, string[] columns = null, int[] Tid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Tracking (NOLOCK)");

				if (Tid != null)
					sql.Where("Tid IN (@0)", Tid);

                return db.Query<PureTracking>(sql);
            }
		}
		
		[TableName("dbo.Pure_Bank")]
		[PrimaryKey("BankId")]
		[ExplicitColumns]
		public partial class PureBank : FountainDb.Record<PureBank>  
		{
			[Column("BankId")] public int Bankid 
			{ 
				get { return _Bankid; }
				set { _Bankid = value; Track("BankId"); }
			}
			int _Bankid;
			[Column("BankName")] public string Bankname 
			{ 
				get { return _Bankname; }
				set { _Bankname = value; Track("BankName"); }
			}
			string _Bankname;
			[Column("BankStatus")] public bool? Bankstatus 
			{ 
				get { return _Bankstatus; }
				set { _Bankstatus = value; Track("BankStatus"); }
			}
			bool? _Bankstatus;
		
			public static IEnumerable<PureBank> Query(Database db, string[] columns = null, int[] Bankid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Bank (NOLOCK)");

				if (Bankid != null)
					sql.Where("BankId IN (@0)", Bankid);

                return db.Query<PureBank>(sql);
            }
		}
		
		[TableName("dbo.Pure_Role")]
		[PrimaryKey("RoleId")]
		[ExplicitColumns]
		public partial class PureRole : FountainDb.Record<PureRole>  
		{
			[Column("RoleId")] public int Roleid 
			{ 
				get { return _Roleid; }
				set { _Roleid = value; Track("RoleId"); }
			}
			int _Roleid;
			[Column("RoleName")] public string Rolename 
			{ 
				get { return _Rolename; }
				set { _Rolename = value; Track("RoleName"); }
			}
			string _Rolename;
			[Column("RoleDesc")] public string Roledesc 
			{ 
				get { return _Roledesc; }
				set { _Roledesc = value; Track("RoleDesc"); }
			}
			string _Roledesc;
			[Column("RoleStatus")] public bool? Rolestatus 
			{ 
				get { return _Rolestatus; }
				set { _Rolestatus = value; Track("RoleStatus"); }
			}
			bool? _Rolestatus;
		
			public static IEnumerable<PureRole> Query(Database db, string[] columns = null, int[] Roleid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Role (NOLOCK)");

				if (Roleid != null)
					sql.Where("RoleId IN (@0)", Roleid);

                return db.Query<PureRole>(sql);
            }
		}
		
		[TableName("dbo.Pure_Country")]
		[PrimaryKey("CountryId")]
		[ExplicitColumns]
		public partial class PureCountry : FountainDb.Record<PureCountry>  
		{
			[Column("CountryId")] public int Countryid 
			{ 
				get { return _Countryid; }
				set { _Countryid = value; Track("CountryId"); }
			}
			int _Countryid;
			[Column("CountryName")] public string Countryname 
			{ 
				get { return _Countryname; }
				set { _Countryname = value; Track("CountryName"); }
			}
			string _Countryname;
			[Column("CountryCode")] public string Countrycode 
			{ 
				get { return _Countrycode; }
				set { _Countrycode = value; Track("CountryCode"); }
			}
			string _Countrycode;
		
			public static IEnumerable<PureCountry> Query(Database db, string[] columns = null, int[] Countryid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Country (NOLOCK)");

				if (Countryid != null)
					sql.Where("CountryId IN (@0)", Countryid);

                return db.Query<PureCountry>(sql);
            }
		}
		
		[TableName("dbo.Pure_RoleMenu")]
		[PrimaryKey("Id")]
		[ExplicitColumns]
		public partial class PureRoleMenu : FountainDb.Record<PureRoleMenu>  
		{
	        [Column] public int Id 
			{ 
				get { return _Id; }
				set { _Id = value; Track("Id"); }
			}
			int _Id;
			[Column("MenuId")] public int? Menuid 
			{ 
				get { return _Menuid; }
				set { _Menuid = value; Track("MenuId"); }
			}
			int? _Menuid;
			[Column("RoleId")] public int? Roleid 
			{ 
				get { return _Roleid; }
				set { _Roleid = value; Track("RoleId"); }
			}
			int? _Roleid;
			[Column("MenuDesc")] public string Menudesc 
			{ 
				get { return _Menudesc; }
				set { _Menudesc = value; Track("MenuDesc"); }
			}
			string _Menudesc;
		
			public static IEnumerable<PureRoleMenu> Query(Database db, string[] columns = null, int[] Id = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_RoleMenu (NOLOCK)");

				if (Id != null)
					sql.Where("Id IN (@0)", Id);

                return db.Query<PureRoleMenu>(sql);
            }
		}
		
		[TableName("dbo.Pure_Remittance")]
		[PrimaryKey("RemId")]
		[ExplicitColumns]
		public partial class PureRemittance : FountainDb.Record<PureRemittance>  
		{
			[Column("RemId")] public int Remid 
			{ 
				get { return _Remid; }
				set { _Remid = value; Track("RemId"); }
			}
			int _Remid;
			[Column("RequestId")] public string Requestid 
			{ 
				get { return _Requestid; }
				set { _Requestid = value; Track("RequestId"); }
			}
			string _Requestid;
			[Column("RemAmount")] public decimal? Remamount 
			{ 
				get { return _Remamount; }
				set { _Remamount = value; Track("RemAmount"); }
			}
			decimal? _Remamount;
			[Column("CreditedBy")] public string Creditedby 
			{ 
				get { return _Creditedby; }
				set { _Creditedby = value; Track("CreditedBy"); }
			}
			string _Creditedby;
			[Column("CreditedOn")] public DateTime? Creditedon 
			{ 
				get { return _Creditedon; }
				set { _Creditedon = value; Track("CreditedOn"); }
			}
			DateTime? _Creditedon;
		
			public static IEnumerable<PureRemittance> Query(Database db, string[] columns = null, int[] Remid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Remittance (NOLOCK)");

				if (Remid != null)
					sql.Where("RemId IN (@0)", Remid);

                return db.Query<PureRemittance>(sql);
            }
		}
		
		[TableName("dbo.Pure_AccountNos")]
		[PrimaryKey("AccountId")]
		[ExplicitColumns]
		public partial class PureAccountNo : FountainDb.Record<PureAccountNo>  
		{
			[Column("AccountId")] public int Accountid 
			{ 
				get { return _Accountid; }
				set { _Accountid = value; Track("AccountId"); }
			}
			int _Accountid;
			[Column("UserBVN")] public string Userbvn 
			{ 
				get { return _Userbvn; }
				set { _Userbvn = value; Track("UserBVN"); }
			}
			string _Userbvn;
			[Column("AccountClass")] public string Accountclass 
			{ 
				get { return _Accountclass; }
				set { _Accountclass = value; Track("AccountClass"); }
			}
			string _Accountclass;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
		
			public static IEnumerable<PureAccountNo> Query(Database db, string[] columns = null, int[] Accountid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_AccountNos (NOLOCK)");

				if (Accountid != null)
					sql.Where("AccountId IN (@0)", Accountid);

                return db.Query<PureAccountNo>(sql);
            }
		}
		
		[TableName("dbo.Pure_States")]
		[PrimaryKey("StateId")]
		[ExplicitColumns]
		public partial class PureState : FountainDb.Record<PureState>  
		{
			[Column("StateId")] public int Stateid 
			{ 
				get { return _Stateid; }
				set { _Stateid = value; Track("StateId"); }
			}
			int _Stateid;
			[Column("StateName")] public string Statename 
			{ 
				get { return _Statename; }
				set { _Statename = value; Track("StateName"); }
			}
			string _Statename;
			[Column("CountryCode")] public string Countrycode 
			{ 
				get { return _Countrycode; }
				set { _Countrycode = value; Track("CountryCode"); }
			}
			string _Countrycode;
		
			public static IEnumerable<PureState> Query(Database db, string[] columns = null, int[] Stateid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_States (NOLOCK)");

				if (Stateid != null)
					sql.Where("StateId IN (@0)", Stateid);

                return db.Query<PureState>(sql);
            }
		}
		
		[TableName("dbo.Pure_Religion")]
		[PrimaryKey("ReligionId")]
		[ExplicitColumns]
		public partial class PureReligion : FountainDb.Record<PureReligion>  
		{
			[Column("ReligionId")] public int Religionid 
			{ 
				get { return _Religionid; }
				set { _Religionid = value; Track("ReligionId"); }
			}
			int _Religionid;
			[Column("ReligionName")] public string Religionname 
			{ 
				get { return _Religionname; }
				set { _Religionname = value; Track("ReligionName"); }
			}
			string _Religionname;
		
			public static IEnumerable<PureReligion> Query(Database db, string[] columns = null, int[] Religionid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Religion (NOLOCK)");

				if (Religionid != null)
					sql.Where("ReligionId IN (@0)", Religionid);

                return db.Query<PureReligion>(sql);
            }
		}
		
		[TableName("dbo.Pure_IDCard")]
		[PrimaryKey("IDNos")]
		[ExplicitColumns]
		public partial class PureIdCard : FountainDb.Record<PureIdCard>  
		{
			[Column("IDNos")] public int Idnos 
			{ 
				get { return _Idnos; }
				set { _Idnos = value; Track("IDNos"); }
			}
			int _Idnos;
			[Column("IDName")] public string Idname 
			{ 
				get { return _Idname; }
				set { _Idname = value; Track("IDName"); }
			}
			string _Idname;
		
			public static IEnumerable<PureIdCard> Query(Database db, string[] columns = null, int[] Idnos = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_IDCard (NOLOCK)");

				if (Idnos != null)
					sql.Where("IDNos IN (@0)", Idnos);

                return db.Query<PureIdCard>(sql);
            }
		}
		
		[TableName("dbo.Pure_TellerTill")]
		[PrimaryKey("DebitId")]
		[ExplicitColumns]
		public partial class PureTellerTill : FountainDb.Record<PureTellerTill>  
		{
			[Column("DebitId")] public int Debitid 
			{ 
				get { return _Debitid; }
				set { _Debitid = value; Track("DebitId"); }
			}
			int _Debitid;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("TellerId")] public string Tellerid 
			{ 
				get { return _Tellerid; }
				set { _Tellerid = value; Track("TellerId"); }
			}
			string _Tellerid;
			[Column("InitialBalance")] public decimal? Initialbalance 
			{ 
				get { return _Initialbalance; }
				set { _Initialbalance = value; Track("InitialBalance"); }
			}
			decimal? _Initialbalance;
	        [Column] public decimal? Amount 
			{ 
				get { return _Amount; }
				set { _Amount = value; Track("Amount"); }
			}
			decimal? _Amount;
			[Column("DRCRIndicator")] public string Drcrindicator 
			{ 
				get { return _Drcrindicator; }
				set { _Drcrindicator = value; Track("DRCRIndicator"); }
			}
			string _Drcrindicator;
			[Column("DebitedDate")] public DateTime? Debiteddate 
			{ 
				get { return _Debiteddate; }
				set { _Debiteddate = value; Track("DebitedDate"); }
			}
			DateTime? _Debiteddate;
			[Column("CreatedBy")] public string Createdby 
			{ 
				get { return _Createdby; }
				set { _Createdby = value; Track("CreatedBy"); }
			}
			string _Createdby;
		
			public static IEnumerable<PureTellerTill> Query(Database db, string[] columns = null, int[] Debitid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_TellerTill (NOLOCK)");

				if (Debitid != null)
					sql.Where("DebitId IN (@0)", Debitid);

                return db.Query<PureTellerTill>(sql);
            }
		}
		
		[TableName("dbo.Pure_UserTitle")]
		[PrimaryKey("TitleId")]
		[ExplicitColumns]
		public partial class PureUserTitle : FountainDb.Record<PureUserTitle>  
		{
			[Column("TitleId")] public int Titleid 
			{ 
				get { return _Titleid; }
				set { _Titleid = value; Track("TitleId"); }
			}
			int _Titleid;
			[Column("TitleName")] public string Titlename 
			{ 
				get { return _Titlename; }
				set { _Titlename = value; Track("TitleName"); }
			}
			string _Titlename;
		
			public static IEnumerable<PureUserTitle> Query(Database db, string[] columns = null, int[] Titleid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_UserTitle (NOLOCK)");

				if (Titleid != null)
					sql.Where("TitleId IN (@0)", Titleid);

                return db.Query<PureUserTitle>(sql);
            }
		}
		
		[TableName("dbo.Pure_UserIdentification")]
		[PrimaryKey("IdNo")]
		[ExplicitColumns]
		public partial class PureUserIdentification : FountainDb.Record<PureUserIdentification>  
		{
			[Column("IdNo")] public int Idno 
			{ 
				get { return _Idno; }
				set { _Idno = value; Track("IdNo"); }
			}
			int _Idno;
			[Column("IdName")] public string Idname 
			{ 
				get { return _Idname; }
				set { _Idname = value; Track("IdName"); }
			}
			string _Idname;
		
			public static IEnumerable<PureUserIdentification> Query(Database db, string[] columns = null, int[] Idno = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_UserIdentification (NOLOCK)");

				if (Idno != null)
					sql.Where("IdNo IN (@0)", Idno);

                return db.Query<PureUserIdentification>(sql);
            }
		}
		
		[TableName("dbo.Pure_Occupation")]
		[PrimaryKey("OccupationId")]
		[ExplicitColumns]
		public partial class PureOccupation : FountainDb.Record<PureOccupation>  
		{
			[Column("OccupationId")] public int Occupationid 
			{ 
				get { return _Occupationid; }
				set { _Occupationid = value; Track("OccupationId"); }
			}
			int _Occupationid;
			[Column("OccupationName")] public string Occupationname 
			{ 
				get { return _Occupationname; }
				set { _Occupationname = value; Track("OccupationName"); }
			}
			string _Occupationname;
		
			public static IEnumerable<PureOccupation> Query(Database db, string[] columns = null, int[] Occupationid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Occupation (NOLOCK)");

				if (Occupationid != null)
					sql.Where("OccupationId IN (@0)", Occupationid);

                return db.Query<PureOccupation>(sql);
            }
		}
		
		[TableName("dbo.Pure_Till_History")]
		[PrimaryKey("HistoryId")]
		[ExplicitColumns]
		public partial class PureTillHistory : FountainDb.Record<PureTillHistory>  
		{
			[Column("HistoryId")] public int Historyid 
			{ 
				get { return _Historyid; }
				set { _Historyid = value; Track("HistoryId"); }
			}
			int _Historyid;
			[Column("AccountName")] public string Accountname 
			{ 
				get { return _Accountname; }
				set { _Accountname = value; Track("AccountName"); }
			}
			string _Accountname;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("CurrencyCode")] public string Currencycode 
			{ 
				get { return _Currencycode; }
				set { _Currencycode = value; Track("CurrencyCode"); }
			}
			string _Currencycode;
			[Column("TellerId")] public string Tellerid 
			{ 
				get { return _Tellerid; }
				set { _Tellerid = value; Track("TellerId"); }
			}
			string _Tellerid;
			[Column("AmtDebited")] public decimal? Amtdebited 
			{ 
				get { return _Amtdebited; }
				set { _Amtdebited = value; Track("AmtDebited"); }
			}
			decimal? _Amtdebited;
			[Column("AmtCredited")] public decimal? Amtcredited 
			{ 
				get { return _Amtcredited; }
				set { _Amtcredited = value; Track("AmtCredited"); }
			}
			decimal? _Amtcredited;
			[Column("ClosedBal")] public decimal? Closedbal 
			{ 
				get { return _Closedbal; }
				set { _Closedbal = value; Track("ClosedBal"); }
			}
			decimal? _Closedbal;
			[Column("TillStatus")] public bool? Tillstatus 
			{ 
				get { return _Tillstatus; }
				set { _Tillstatus = value; Track("TillStatus"); }
			}
			bool? _Tillstatus;
			[Column("CreatedBy")] public string Createdby 
			{ 
				get { return _Createdby; }
				set { _Createdby = value; Track("CreatedBy"); }
			}
			string _Createdby;
			[Column("CreatedDate")] public DateTime? Createddate 
			{ 
				get { return _Createddate; }
				set { _Createddate = value; Track("CreatedDate"); }
			}
			DateTime? _Createddate;
			[Column("TranDate")] public DateTime? Trandate 
			{ 
				get { return _Trandate; }
				set { _Trandate = value; Track("TranDate"); }
			}
			DateTime? _Trandate;
		
			public static IEnumerable<PureTillHistory> Query(Database db, string[] columns = null, int[] Historyid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Till_History (NOLOCK)");

				if (Historyid != null)
					sql.Where("HistoryId IN (@0)", Historyid);

                return db.Query<PureTillHistory>(sql);
            }
		}
		
		[TableName("dbo.Pure_Customer_Info")]
		[PrimaryKey("CustomerId")]
		[ExplicitColumns]
		public partial class PureCustomerInfo : FountainDb.Record<PureCustomerInfo>  
		{
			[Column("CustomerId")] public int Customerid 
			{ 
				get { return _Customerid; }
				set { _Customerid = value; Track("CustomerId"); }
			}
			int _Customerid;
			[Column("FirstName")] public string Firstname 
			{ 
				get { return _Firstname; }
				set { _Firstname = value; Track("FirstName"); }
			}
			string _Firstname;
			[Column("MiddleName")] public string Middlename 
			{ 
				get { return _Middlename; }
				set { _Middlename = value; Track("MiddleName"); }
			}
			string _Middlename;
			[Column("LastName")] public string Lastname 
			{ 
				get { return _Lastname; }
				set { _Lastname = value; Track("LastName"); }
			}
			string _Lastname;
			[Column("UserEmail")] public string Useremail 
			{ 
				get { return _Useremail; }
				set { _Useremail = value; Track("UserEmail"); }
			}
			string _Useremail;
			[Column("PhoneNos1")] public string Phonenos1 
			{ 
				get { return _Phonenos1; }
				set { _Phonenos1 = value; Track("PhoneNos1"); }
			}
			string _Phonenos1;
			[Column("PhoneNos2")] public string Phonenos2 
			{ 
				get { return _Phonenos2; }
				set { _Phonenos2 = value; Track("PhoneNos2"); }
			}
			string _Phonenos2;
			[Column("MaidenName")] public string Maidenname 
			{ 
				get { return _Maidenname; }
				set { _Maidenname = value; Track("MaidenName"); }
			}
			string _Maidenname;
			[Column("UserSex")] public string Usersex 
			{ 
				get { return _Usersex; }
				set { _Usersex = value; Track("UserSex"); }
			}
			string _Usersex;
			[Column("UserLGA")] public string Userlga 
			{ 
				get { return _Userlga; }
				set { _Userlga = value; Track("UserLGA"); }
			}
			string _Userlga;
			[Column("IDIssueAuth")] public string Idissueauth 
			{ 
				get { return _Idissueauth; }
				set { _Idissueauth = value; Track("IDIssueAuth"); }
			}
			string _Idissueauth;
			[Column("AccountImg")] public string Accountimg 
			{ 
				get { return _Accountimg; }
				set { _Accountimg = value; Track("AccountImg"); }
			}
			string _Accountimg;
			[Column("HomeAddress")] public string Homeaddress 
			{ 
				get { return _Homeaddress; }
				set { _Homeaddress = value; Track("HomeAddress"); }
			}
			string _Homeaddress;
			[Column("StateOrigin")] public int? Stateorigin 
			{ 
				get { return _Stateorigin; }
				set { _Stateorigin = value; Track("StateOrigin"); }
			}
			int? _Stateorigin;
			[Column("DOB")] public DateTime? Dob 
			{ 
				get { return _Dob; }
				set { _Dob = value; Track("DOB"); }
			}
			DateTime? _Dob;
			[Column("MaritalStatus")] public string Maritalstatus 
			{ 
				get { return _Maritalstatus; }
				set { _Maritalstatus = value; Track("MaritalStatus"); }
			}
			string _Maritalstatus;
			[Column("OccupationId")] public int? Occupationid 
			{ 
				get { return _Occupationid; }
				set { _Occupationid = value; Track("OccupationId"); }
			}
			int? _Occupationid;
			[Column("JobTitle")] public string Jobtitle 
			{ 
				get { return _Jobtitle; }
				set { _Jobtitle = value; Track("JobTitle"); }
			}
			string _Jobtitle;
			[Column("IncomeRange")] public string Incomerange 
			{ 
				get { return _Incomerange; }
				set { _Incomerange = value; Track("IncomeRange"); }
			}
			string _Incomerange;
			[Column("ReligionId")] public int? Religionid 
			{ 
				get { return _Religionid; }
				set { _Religionid = value; Track("ReligionId"); }
			}
			int? _Religionid;
	        [Column] public string Nationality 
			{ 
				get { return _Nationality; }
				set { _Nationality = value; Track("Nationality"); }
			}
			string _Nationality;
			[Column("IDNos")] public int? Idnos 
			{ 
				get { return _Idnos; }
				set { _Idnos = value; Track("IDNos"); }
			}
			int? _Idnos;
			[Column("IDIssueDate")] public DateTime? Idissuedate 
			{ 
				get { return _Idissuedate; }
				set { _Idissuedate = value; Track("IDIssueDate"); }
			}
			DateTime? _Idissuedate;
			[Column("IDExpiryDate")] public DateTime? Idexpirydate 
			{ 
				get { return _Idexpirydate; }
				set { _Idexpirydate = value; Track("IDExpiryDate"); }
			}
			DateTime? _Idexpirydate;
			[Column("UserBVN")] public string Userbvn 
			{ 
				get { return _Userbvn; }
				set { _Userbvn = value; Track("UserBVN"); }
			}
			string _Userbvn;
			[Column("IDDetails")] public string Iddetails 
			{ 
				get { return _Iddetails; }
				set { _Iddetails = value; Track("IDDetails"); }
			}
			string _Iddetails;
			[Column("EmploymentDate")] public DateTime? Employmentdate 
			{ 
				get { return _Employmentdate; }
				set { _Employmentdate = value; Track("EmploymentDate"); }
			}
			DateTime? _Employmentdate;
			[Column("AccountType")] public int? Accounttype 
			{ 
				get { return _Accounttype; }
				set { _Accounttype = value; Track("AccountType"); }
			}
			int? _Accounttype;
			[Column("OtherBankId")] public int? Otherbankid 
			{ 
				get { return _Otherbankid; }
				set { _Otherbankid = value; Track("OtherBankId"); }
			}
			int? _Otherbankid;
			[Column("OtherAccountNos")] public string Otheraccountnos 
			{ 
				get { return _Otheraccountnos; }
				set { _Otheraccountnos = value; Track("OtherAccountNos"); }
			}
			string _Otheraccountnos;
			[Column("OfficeAddress")] public string Officeaddress 
			{ 
				get { return _Officeaddress; }
				set { _Officeaddress = value; Track("OfficeAddress"); }
			}
			string _Officeaddress;
			[Column("NextOfKin")] public string Nextofkin 
			{ 
				get { return _Nextofkin; }
				set { _Nextofkin = value; Track("NextOfKin"); }
			}
			string _Nextofkin;
			[Column("KNumber")] public string Knumber 
			{ 
				get { return _Knumber; }
				set { _Knumber = value; Track("KNumber"); }
			}
			string _Knumber;
			[Column("KRelationship")] public string Krelationship 
			{ 
				get { return _Krelationship; }
				set { _Krelationship = value; Track("KRelationship"); }
			}
			string _Krelationship;
			[Column("KAddress")] public string Kaddress 
			{ 
				get { return _Kaddress; }
				set { _Kaddress = value; Track("KAddress"); }
			}
			string _Kaddress;
			[Column("RefName")] public string Refname 
			{ 
				get { return _Refname; }
				set { _Refname = value; Track("RefName"); }
			}
			string _Refname;
			[Column("ReasonForAccount")] public string Reasonforaccount 
			{ 
				get { return _Reasonforaccount; }
				set { _Reasonforaccount = value; Track("ReasonForAccount"); }
			}
			string _Reasonforaccount;
			[Column("AccountSign")] public string Accountsign 
			{ 
				get { return _Accountsign; }
				set { _Accountsign = value; Track("AccountSign"); }
			}
			string _Accountsign;
			[Column("AccountName")] public string Accountname 
			{ 
				get { return _Accountname; }
				set { _Accountname = value; Track("AccountName"); }
			}
			string _Accountname;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("AccountStatus")] public bool? Accountstatus 
			{ 
				get { return _Accountstatus; }
				set { _Accountstatus = value; Track("AccountStatus"); }
			}
			bool? _Accountstatus;
			[Column("CreatedBy")] public string Createdby 
			{ 
				get { return _Createdby; }
				set { _Createdby = value; Track("CreatedBy"); }
			}
			string _Createdby;
			[Column("CreatedOn")] public DateTime? Createdon 
			{ 
				get { return _Createdon; }
				set { _Createdon = value; Track("CreatedOn"); }
			}
			DateTime? _Createdon;
			[Column("ModifiedBy")] public string Modifiedby 
			{ 
				get { return _Modifiedby; }
				set { _Modifiedby = value; Track("ModifiedBy"); }
			}
			string _Modifiedby;
			[Column("ModifiedOn")] public DateTime? Modifiedon 
			{ 
				get { return _Modifiedon; }
				set { _Modifiedon = value; Track("ModifiedOn"); }
			}
			DateTime? _Modifiedon;
			[Column("ApprovedBy")] public string Approvedby 
			{ 
				get { return _Approvedby; }
				set { _Approvedby = value; Track("ApprovedBy"); }
			}
			string _Approvedby;
			[Column("ApprovedOn")] public DateTime? Approvedon 
			{ 
				get { return _Approvedon; }
				set { _Approvedon = value; Track("ApprovedOn"); }
			}
			DateTime? _Approvedon;
		
			public static IEnumerable<PureCustomerInfo> Query(Database db, string[] columns = null, int[] Customerid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Customer_Info (NOLOCK)");

				if (Customerid != null)
					sql.Where("CustomerId IN (@0)", Customerid);

                return db.Query<PureCustomerInfo>(sql);
            }
		}
		
		[TableName("dbo.Pure_Account_Details")]
		[PrimaryKey("Id")]
		[ExplicitColumns]
		public partial class PureAccountDetail : FountainDb.Record<PureAccountDetail>  
		{
	        [Column] public int Id 
			{ 
				get { return _Id; }
				set { _Id = value; Track("Id"); }
			}
			int _Id;
			[Column("CustomerId")] public int? Customerid 
			{ 
				get { return _Customerid; }
				set { _Customerid = value; Track("CustomerId"); }
			}
			int? _Customerid;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("AccountBal")] public decimal? Accountbal 
			{ 
				get { return _Accountbal; }
				set { _Accountbal = value; Track("AccountBal"); }
			}
			decimal? _Accountbal;
			[Column("ModifiedBy")] public string Modifiedby 
			{ 
				get { return _Modifiedby; }
				set { _Modifiedby = value; Track("ModifiedBy"); }
			}
			string _Modifiedby;
			[Column("ModifiedOn")] public DateTime? Modifiedon 
			{ 
				get { return _Modifiedon; }
				set { _Modifiedon = value; Track("ModifiedOn"); }
			}
			DateTime? _Modifiedon;
		
			public static IEnumerable<PureAccountDetail> Query(Database db, string[] columns = null, int[] Id = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Account_Details (NOLOCK)");

				if (Id != null)
					sql.Where("Id IN (@0)", Id);

                return db.Query<PureAccountDetail>(sql);
            }
		}
		
		[TableName("dbo.Pure_Statement")]
		[PrimaryKey("Id")]
		[ExplicitColumns]
		public partial class PureStatement : FountainDb.Record<PureStatement>  
		{
	        [Column] public int Id 
			{ 
				get { return _Id; }
				set { _Id = value; Track("Id"); }
			}
			int _Id;
			[Column("ReferenceId")] public string Referenceid 
			{ 
				get { return _Referenceid; }
				set { _Referenceid = value; Track("ReferenceId"); }
			}
			string _Referenceid;
			[Column("TransactionDetails")] public string Transactiondetails 
			{ 
				get { return _Transactiondetails; }
				set { _Transactiondetails = value; Track("TransactionDetails"); }
			}
			string _Transactiondetails;
			[Column("AccountNo")] public string Accountno 
			{ 
				get { return _Accountno; }
				set { _Accountno = value; Track("AccountNo"); }
			}
			string _Accountno;
	        [Column] public decimal? Deposit 
			{ 
				get { return _Deposit; }
				set { _Deposit = value; Track("Deposit"); }
			}
			decimal? _Deposit;
	        [Column] public decimal? Withdrawal 
			{ 
				get { return _Withdrawal; }
				set { _Withdrawal = value; Track("Withdrawal"); }
			}
			decimal? _Withdrawal;
			[Column("AccountBal")] public decimal? Accountbal 
			{ 
				get { return _Accountbal; }
				set { _Accountbal = value; Track("AccountBal"); }
			}
			decimal? _Accountbal;
			[Column("ValueDate")] public DateTime? Valuedate 
			{ 
				get { return _Valuedate; }
				set { _Valuedate = value; Track("ValueDate"); }
			}
			DateTime? _Valuedate;
		
			public static IEnumerable<PureStatement> Query(Database db, string[] columns = null, int[] Id = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Statement (NOLOCK)");

				if (Id != null)
					sql.Where("Id IN (@0)", Id);

                return db.Query<PureStatement>(sql);
            }
		}
		
		[TableName("dbo.Pure_TransactionLog")]
		[PrimaryKey("TransId")]
		[ExplicitColumns]
		public partial class PureTransactionLog : FountainDb.Record<PureTransactionLog>  
		{
			[Column("TransId")] public int Transid 
			{ 
				get { return _Transid; }
				set { _Transid = value; Track("TransId"); }
			}
			int _Transid;
			[Column("RequestId")] public string Requestid 
			{ 
				get { return _Requestid; }
				set { _Requestid = value; Track("RequestId"); }
			}
			string _Requestid;
			[Column("SourceAccount")] public string Sourceaccount 
			{ 
				get { return _Sourceaccount; }
				set { _Sourceaccount = value; Track("SourceAccount"); }
			}
			string _Sourceaccount;
			[Column("DestinationAccount")] public string Destinationaccount 
			{ 
				get { return _Destinationaccount; }
				set { _Destinationaccount = value; Track("DestinationAccount"); }
			}
			string _Destinationaccount;
	        [Column] public string Narration 
			{ 
				get { return _Narration; }
				set { _Narration = value; Track("Narration"); }
			}
			string _Narration;
	        [Column] public decimal? Amount 
			{ 
				get { return _Amount; }
				set { _Amount = value; Track("Amount"); }
			}
			decimal? _Amount;
			[Column("TranStatus")] public string Transtatus 
			{ 
				get { return _Transtatus; }
				set { _Transtatus = value; Track("TranStatus"); }
			}
			string _Transtatus;
			[Column("CustomerId")] public int? Customerid 
			{ 
				get { return _Customerid; }
				set { _Customerid = value; Track("CustomerId"); }
			}
			int? _Customerid;
			[Column("TranType")] public string Trantype 
			{ 
				get { return _Trantype; }
				set { _Trantype = value; Track("TranType"); }
			}
			string _Trantype;
			[Column("TranCurrency")] public string Trancurrency 
			{ 
				get { return _Trancurrency; }
				set { _Trancurrency = value; Track("TranCurrency"); }
			}
			string _Trancurrency;
			[Column("TranInitiator")] public string Traninitiator 
			{ 
				get { return _Traninitiator; }
				set { _Traninitiator = value; Track("TranInitiator"); }
			}
			string _Traninitiator;
			[Column("TranApprover")] public string Tranapprover 
			{ 
				get { return _Tranapprover; }
				set { _Tranapprover = value; Track("TranApprover"); }
			}
			string _Tranapprover;
			[Column("TranDate")] public DateTime? Trandate 
			{ 
				get { return _Trandate; }
				set { _Trandate = value; Track("TranDate"); }
			}
			DateTime? _Trandate;
			[Column("ApprovedDate")] public DateTime? Approveddate 
			{ 
				get { return _Approveddate; }
				set { _Approveddate = value; Track("ApprovedDate"); }
			}
			DateTime? _Approveddate;
		
			public static IEnumerable<PureTransactionLog> Query(Database db, string[] columns = null, int[] Transid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_TransactionLog (NOLOCK)");

				if (Transid != null)
					sql.Where("TransId IN (@0)", Transid);

                return db.Query<PureTransactionLog>(sql);
            }
		}
		
		[TableName("dbo.Pure_FlexRole")]
		[ExplicitColumns]
		public partial class PureFlexRole : FountainDb.Record<PureFlexRole>  
		{
			[Column("FlexId")] public int? Flexid 
			{ 
				get { return _Flexid; }
				set { _Flexid = value; Track("FlexId"); }
			}
			int? _Flexid;
			[Column("FlexName")] public string Flexname 
			{ 
				get { return _Flexname; }
				set { _Flexname = value; Track("FlexName"); }
			}
			string _Flexname;
			[Column("FlexDesc")] public string Flexdesc 
			{ 
				get { return _Flexdesc; }
				set { _Flexdesc = value; Track("FlexDesc"); }
			}
			string _Flexdesc;
		}
		
		[TableName("dbo.Pure_Post_Request")]
		[PrimaryKey("TranId")]
		[ExplicitColumns]
		public partial class PurePostRequest : FountainDb.Record<PurePostRequest>  
		{
			[Column("TranId")] public int Tranid 
			{ 
				get { return _Tranid; }
				set { _Tranid = value; Track("TranId"); }
			}
			int _Tranid;
			[Column("RequestId")] public string Requestid 
			{ 
				get { return _Requestid; }
				set { _Requestid = value; Track("RequestId"); }
			}
			string _Requestid;
			[Column("AccountName")] public string Accountname 
			{ 
				get { return _Accountname; }
				set { _Accountname = value; Track("AccountName"); }
			}
			string _Accountname;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("DRCRIndicator")] public string Drcrindicator 
			{ 
				get { return _Drcrindicator; }
				set { _Drcrindicator = value; Track("DRCRIndicator"); }
			}
			string _Drcrindicator;
			[Column("TranAmount")] public decimal? Tranamount 
			{ 
				get { return _Tranamount; }
				set { _Tranamount = value; Track("TranAmount"); }
			}
			decimal? _Tranamount;
			[Column("TranStatus")] public string Transtatus 
			{ 
				get { return _Transtatus; }
				set { _Transtatus = value; Track("TranStatus"); }
			}
			string _Transtatus;
		
			public static IEnumerable<PurePostRequest> Query(Database db, string[] columns = null, int[] Tranid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Post_Request (NOLOCK)");

				if (Tranid != null)
					sql.Where("TranId IN (@0)", Tranid);

                return db.Query<PurePostRequest>(sql);
            }
		}
		
		[TableName("dbo.Pure_Loan_Category")]
		[PrimaryKey("LoanCateId")]
		[ExplicitColumns]
		public partial class PureLoanCategory : FountainDb.Record<PureLoanCategory>  
		{
			[Column("LoanCateId")] public int Loancateid 
			{ 
				get { return _Loancateid; }
				set { _Loancateid = value; Track("LoanCateId"); }
			}
			int _Loancateid;
			[Column("LoanName")] public string Loanname 
			{ 
				get { return _Loanname; }
				set { _Loanname = value; Track("LoanName"); }
			}
			string _Loanname;
			[Column("LoanDesc")] public string Loandesc 
			{ 
				get { return _Loandesc; }
				set { _Loandesc = value; Track("LoanDesc"); }
			}
			string _Loandesc;
			[Column("LoanStatus")] public bool? Loanstatus 
			{ 
				get { return _Loanstatus; }
				set { _Loanstatus = value; Track("LoanStatus"); }
			}
			bool? _Loanstatus;
		
			public static IEnumerable<PureLoanCategory> Query(Database db, string[] columns = null, int[] Loancateid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Loan_Category (NOLOCK)");

				if (Loancateid != null)
					sql.Where("LoanCateId IN (@0)", Loancateid);

                return db.Query<PureLoanCategory>(sql);
            }
		}
		
		[TableName("dbo.Pure_Currency")]
		[PrimaryKey("CurrencyId")]
		[ExplicitColumns]
		public partial class PureCurrency : FountainDb.Record<PureCurrency>  
		{
			[Column("CurrencyId")] public int Currencyid 
			{ 
				get { return _Currencyid; }
				set { _Currencyid = value; Track("CurrencyId"); }
			}
			int _Currencyid;
			[Column("CurrencyName")] public string Currencyname 
			{ 
				get { return _Currencyname; }
				set { _Currencyname = value; Track("CurrencyName"); }
			}
			string _Currencyname;
			[Column("CurrencyISO")] public string Currencyiso 
			{ 
				get { return _Currencyiso; }
				set { _Currencyiso = value; Track("CurrencyISO"); }
			}
			string _Currencyiso;
		
			public static IEnumerable<PureCurrency> Query(Database db, string[] columns = null, int[] Currencyid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Currency (NOLOCK)");

				if (Currencyid != null)
					sql.Where("CurrencyId IN (@0)", Currencyid);

                return db.Query<PureCurrency>(sql);
            }
		}
		
		[TableName("dbo.Pure_Deposit")]
		[PrimaryKey("DepositId")]
		[ExplicitColumns]
		public partial class PureDeposit : FountainDb.Record<PureDeposit>  
		{
			[Column("DepositId")] public int Depositid 
			{ 
				get { return _Depositid; }
				set { _Depositid = value; Track("DepositId"); }
			}
			int _Depositid;
			[Column("RequestId")] public string Requestid 
			{ 
				get { return _Requestid; }
				set { _Requestid = value; Track("RequestId"); }
			}
			string _Requestid;
			[Column("AccountTitle")] public string Accounttitle 
			{ 
				get { return _Accounttitle; }
				set { _Accounttitle = value; Track("AccountTitle"); }
			}
			string _Accounttitle;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("DepositorName")] public string Depositorname 
			{ 
				get { return _Depositorname; }
				set { _Depositorname = value; Track("DepositorName"); }
			}
			string _Depositorname;
			[Column("DepositorNos")] public string Depositornos 
			{ 
				get { return _Depositornos; }
				set { _Depositornos = value; Track("DepositorNos"); }
			}
			string _Depositornos;
	        [Column] public string Narration 
			{ 
				get { return _Narration; }
				set { _Narration = value; Track("Narration"); }
			}
			string _Narration;
	        [Column] public decimal? Amount 
			{ 
				get { return _Amount; }
				set { _Amount = value; Track("Amount"); }
			}
			decimal? _Amount;
			[Column("CurrencyISO")] public string Currencyiso 
			{ 
				get { return _Currencyiso; }
				set { _Currencyiso = value; Track("CurrencyISO"); }
			}
			string _Currencyiso;
	        [Column] public string Status 
			{ 
				get { return _Status; }
				set { _Status = value; Track("Status"); }
			}
			string _Status;
	        [Column] public string Processor 
			{ 
				get { return _Processor; }
				set { _Processor = value; Track("Processor"); }
			}
			string _Processor;
			[Column("DepositedDate")] public DateTime? Depositeddate 
			{ 
				get { return _Depositeddate; }
				set { _Depositeddate = value; Track("DepositedDate"); }
			}
			DateTime? _Depositeddate;
		
			public static IEnumerable<PureDeposit> Query(Database db, string[] columns = null, int[] Depositid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Deposit (NOLOCK)");

				if (Depositid != null)
					sql.Where("DepositId IN (@0)", Depositid);

                return db.Query<PureDeposit>(sql);
            }
		}
		
		[TableName("dbo.Pure_TillAccount")]
		[PrimaryKey("TillId")]
		[ExplicitColumns]
		public partial class PureTillAccount : FountainDb.Record<PureTillAccount>  
		{
			[Column("TillId")] public int Tillid 
			{ 
				get { return _Tillid; }
				set { _Tillid = value; Track("TillId"); }
			}
			int _Tillid;
			[Column("AccountName")] public string Accountname 
			{ 
				get { return _Accountname; }
				set { _Accountname = value; Track("AccountName"); }
			}
			string _Accountname;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("AccountBal")] public decimal? Accountbal 
			{ 
				get { return _Accountbal; }
				set { _Accountbal = value; Track("AccountBal"); }
			}
			decimal? _Accountbal;
			[Column("AmountDebited")] public decimal? Amountdebited 
			{ 
				get { return _Amountdebited; }
				set { _Amountdebited = value; Track("AmountDebited"); }
			}
			decimal? _Amountdebited;
			[Column("CurrencyCode")] public string Currencycode 
			{ 
				get { return _Currencycode; }
				set { _Currencycode = value; Track("CurrencyCode"); }
			}
			string _Currencycode;
			[Column("TellerId")] public string Tellerid 
			{ 
				get { return _Tellerid; }
				set { _Tellerid = value; Track("TellerId"); }
			}
			string _Tellerid;
			[Column("AccountStatus")] public bool? Accountstatus 
			{ 
				get { return _Accountstatus; }
				set { _Accountstatus = value; Track("AccountStatus"); }
			}
			bool? _Accountstatus;
			[Column("DRCRIndicator")] public string Drcrindicator 
			{ 
				get { return _Drcrindicator; }
				set { _Drcrindicator = value; Track("DRCRIndicator"); }
			}
			string _Drcrindicator;
			[Column("CreatedOn")] public DateTime? Createdon 
			{ 
				get { return _Createdon; }
				set { _Createdon = value; Track("CreatedOn"); }
			}
			DateTime? _Createdon;
			[Column("CreditedBy")] public string Creditedby 
			{ 
				get { return _Creditedby; }
				set { _Creditedby = value; Track("CreditedBy"); }
			}
			string _Creditedby;
		
			public static IEnumerable<PureTillAccount> Query(Database db, string[] columns = null, int[] Tillid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_TillAccount (NOLOCK)");

				if (Tillid != null)
					sql.Where("TillId IN (@0)", Tillid);

                return db.Query<PureTillAccount>(sql);
            }
		}
		
		[TableName("dbo.Pure_Withdrawal")]
		[PrimaryKey("WithdrawalId")]
		[ExplicitColumns]
		public partial class PureWithdrawal : FountainDb.Record<PureWithdrawal>  
		{
			[Column("WithdrawalId")] public int Withdrawalid 
			{ 
				get { return _Withdrawalid; }
				set { _Withdrawalid = value; Track("WithdrawalId"); }
			}
			int _Withdrawalid;
			[Column("RequestId")] public string Requestid 
			{ 
				get { return _Requestid; }
				set { _Requestid = value; Track("RequestId"); }
			}
			string _Requestid;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
	        [Column] public decimal? Amount 
			{ 
				get { return _Amount; }
				set { _Amount = value; Track("Amount"); }
			}
			decimal? _Amount;
			[Column("CurrencyISO")] public string Currencyiso 
			{ 
				get { return _Currencyiso; }
				set { _Currencyiso = value; Track("CurrencyISO"); }
			}
			string _Currencyiso;
			[Column("TranStatus")] public string Transtatus 
			{ 
				get { return _Transtatus; }
				set { _Transtatus = value; Track("TranStatus"); }
			}
			string _Transtatus;
	        [Column] public string Processor 
			{ 
				get { return _Processor; }
				set { _Processor = value; Track("Processor"); }
			}
			string _Processor;
			[Column("WithdrawalDate")] public DateTime? Withdrawaldate 
			{ 
				get { return _Withdrawaldate; }
				set { _Withdrawaldate = value; Track("WithdrawalDate"); }
			}
			DateTime? _Withdrawaldate;
		
			public static IEnumerable<PureWithdrawal> Query(Database db, string[] columns = null, int[] Withdrawalid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Withdrawal (NOLOCK)");

				if (Withdrawalid != null)
					sql.Where("WithdrawalId IN (@0)", Withdrawalid);

                return db.Query<PureWithdrawal>(sql);
            }
		}
		
		[TableName("dbo.Pure_Repayment")]
		[PrimaryKey("RepayId")]
		[ExplicitColumns]
		public partial class PureRepayment : FountainDb.Record<PureRepayment>  
		{
			[Column("RepayId")] public int Repayid 
			{ 
				get { return _Repayid; }
				set { _Repayid = value; Track("RepayId"); }
			}
			int _Repayid;
			[Column("CustomerId")] public string Customerid 
			{ 
				get { return _Customerid; }
				set { _Customerid = value; Track("CustomerId"); }
			}
			string _Customerid;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("LoanAmt")] public decimal? Loanamt 
			{ 
				get { return _Loanamt; }
				set { _Loanamt = value; Track("LoanAmt"); }
			}
			decimal? _Loanamt;
			[Column("AmountToBePaid")] public decimal? Amounttobepaid 
			{ 
				get { return _Amounttobepaid; }
				set { _Amounttobepaid = value; Track("AmountToBePaid"); }
			}
			decimal? _Amounttobepaid;
			[Column("AmountCredit")] public decimal? Amountcredit 
			{ 
				get { return _Amountcredit; }
				set { _Amountcredit = value; Track("AmountCredit"); }
			}
			decimal? _Amountcredit;
			[Column("TransRef")] public string Transref 
			{ 
				get { return _Transref; }
				set { _Transref = value; Track("TransRef"); }
			}
			string _Transref;
			[Column("ReceiptNos")] public string Receiptnos 
			{ 
				get { return _Receiptnos; }
				set { _Receiptnos = value; Track("ReceiptNos"); }
			}
			string _Receiptnos;
			[Column("CreditedOn")] public DateTime? Creditedon 
			{ 
				get { return _Creditedon; }
				set { _Creditedon = value; Track("CreditedOn"); }
			}
			DateTime? _Creditedon;
		
			public static IEnumerable<PureRepayment> Query(Database db, string[] columns = null, int[] Repayid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Repayment (NOLOCK)");

				if (Repayid != null)
					sql.Where("RepayId IN (@0)", Repayid);

                return db.Query<PureRepayment>(sql);
            }
		}
		
		[TableName("dbo.Pure_Loan")]
		[PrimaryKey("LoanId")]
		[ExplicitColumns]
		public partial class PureLoan : FountainDb.Record<PureLoan>  
		{
			[Column("LoanId")] public int Loanid 
			{ 
				get { return _Loanid; }
				set { _Loanid = value; Track("LoanId"); }
			}
			int _Loanid;
			[Column("LoanCateId")] public int? Loancateid 
			{ 
				get { return _Loancateid; }
				set { _Loancateid = value; Track("LoanCateId"); }
			}
			int? _Loancateid;
			[Column("AccountNos")] public string Accountnos 
			{ 
				get { return _Accountnos; }
				set { _Accountnos = value; Track("AccountNos"); }
			}
			string _Accountnos;
			[Column("LoanAmount")] public decimal? Loanamount 
			{ 
				get { return _Loanamount; }
				set { _Loanamount = value; Track("LoanAmount"); }
			}
			decimal? _Loanamount;
			[Column("LoanInterest")] public decimal? Loaninterest 
			{ 
				get { return _Loaninterest; }
				set { _Loaninterest = value; Track("LoanInterest"); }
			}
			decimal? _Loaninterest;
			[Column("LoanInterestWeek")] public decimal? Loaninterestweek 
			{ 
				get { return _Loaninterestweek; }
				set { _Loaninterestweek = value; Track("LoanInterestWeek"); }
			}
			decimal? _Loaninterestweek;
			[Column("LoanDuration")] public string Loanduration 
			{ 
				get { return _Loanduration; }
				set { _Loanduration = value; Track("LoanDuration"); }
			}
			string _Loanduration;
			[Column("Guarantor1Name")] public string Guarantor1name 
			{ 
				get { return _Guarantor1name; }
				set { _Guarantor1name = value; Track("Guarantor1Name"); }
			}
			string _Guarantor1name;
			[Column("Guarantor1PhoneNos")] public string Guarantor1phonenos 
			{ 
				get { return _Guarantor1phonenos; }
				set { _Guarantor1phonenos = value; Track("Guarantor1PhoneNos"); }
			}
			string _Guarantor1phonenos;
			[Column("Guarantor2Name")] public string Guarantor2name 
			{ 
				get { return _Guarantor2name; }
				set { _Guarantor2name = value; Track("Guarantor2Name"); }
			}
			string _Guarantor2name;
			[Column("Guarantor2PhoneNos")] public string Guarantor2phonenos 
			{ 
				get { return _Guarantor2phonenos; }
				set { _Guarantor2phonenos = value; Track("Guarantor2PhoneNos"); }
			}
			string _Guarantor2phonenos;
			[Column("LoanStatus")] public string Loanstatus 
			{ 
				get { return _Loanstatus; }
				set { _Loanstatus = value; Track("LoanStatus"); }
			}
			string _Loanstatus;
			[Column("RepaymentStatus")] public string Repaymentstatus 
			{ 
				get { return _Repaymentstatus; }
				set { _Repaymentstatus = value; Track("RepaymentStatus"); }
			}
			string _Repaymentstatus;
	        [Column] public string Processor 
			{ 
				get { return _Processor; }
				set { _Processor = value; Track("Processor"); }
			}
			string _Processor;
	        [Column] public string Approver 
			{ 
				get { return _Approver; }
				set { _Approver = value; Track("Approver"); }
			}
			string _Approver;
			[Column("ProcessedDate")] public DateTime? Processeddate 
			{ 
				get { return _Processeddate; }
				set { _Processeddate = value; Track("ProcessedDate"); }
			}
			DateTime? _Processeddate;
			[Column("ApprovedDate")] public DateTime? Approveddate 
			{ 
				get { return _Approveddate; }
				set { _Approveddate = value; Track("ApprovedDate"); }
			}
			DateTime? _Approveddate;
		
			public static IEnumerable<PureLoan> Query(Database db, string[] columns = null, int[] Loanid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Loan (NOLOCK)");

				if (Loanid != null)
					sql.Where("LoanId IN (@0)", Loanid);

                return db.Query<PureLoan>(sql);
            }
		}
		
		[TableName("dbo.Pure_Menu")]
		[ExplicitColumns]
		public partial class PureMenu : FountainDb.Record<PureMenu>  
		{
			[Column("MenuId")] public int Menuid 
			{ 
				get { return _Menuid; }
				set { _Menuid = value; Track("MenuId"); }
			}
			int _Menuid;
			[Column("MenuName")] public string Menuname 
			{ 
				get { return _Menuname; }
				set { _Menuname = value; Track("MenuName"); }
			}
			string _Menuname;
			[Column("MenuURL")] public string Menuurl 
			{ 
				get { return _Menuurl; }
				set { _Menuurl = value; Track("MenuURL"); }
			}
			string _Menuurl;
			[Column("MenuDesc")] public string Menudesc 
			{ 
				get { return _Menudesc; }
				set { _Menudesc = value; Track("MenuDesc"); }
			}
			string _Menudesc;
			[Column("ParentId")] public int? Parentid 
			{ 
				get { return _Parentid; }
				set { _Parentid = value; Track("ParentId"); }
			}
			int? _Parentid;
	        [Column] public int? Sequence 
			{ 
				get { return _Sequence; }
				set { _Sequence = value; Track("Sequence"); }
			}
			int? _Sequence;
			[Column("ExternalURL")] public string Externalurl 
			{ 
				get { return _Externalurl; }
				set { _Externalurl = value; Track("ExternalURL"); }
			}
			string _Externalurl;
			[Column("MenuStatus")] public bool? Menustatus 
			{ 
				get { return _Menustatus; }
				set { _Menustatus = value; Track("MenuStatus"); }
			}
			bool? _Menustatus;
			[Column("LinkIcon")] public string Linkicon 
			{ 
				get { return _Linkicon; }
				set { _Linkicon = value; Track("LinkIcon"); }
			}
			string _Linkicon;
			[Column("RankId")] public int? Rankid 
			{ 
				get { return _Rankid; }
				set { _Rankid = value; Track("RankId"); }
			}
			int? _Rankid;
		}
		
		[TableName("dbo.Pure_Account_Category")]
		[PrimaryKey("AccountId")]
		[ExplicitColumns]
		public partial class PureAccountCategory : FountainDb.Record<PureAccountCategory>  
		{
			[Column("AccountId")] public int Accountid 
			{ 
				get { return _Accountid; }
				set { _Accountid = value; Track("AccountId"); }
			}
			int _Accountid;
			[Column("AccountTitle")] public string Accounttitle 
			{ 
				get { return _Accounttitle; }
				set { _Accounttitle = value; Track("AccountTitle"); }
			}
			string _Accounttitle;
			[Column("AccountDesc")] public string Accountdesc 
			{ 
				get { return _Accountdesc; }
				set { _Accountdesc = value; Track("AccountDesc"); }
			}
			string _Accountdesc;
			[Column("AccountStatus")] public int? Accountstatus 
			{ 
				get { return _Accountstatus; }
				set { _Accountstatus = value; Track("AccountStatus"); }
			}
			int? _Accountstatus;
		
			public static IEnumerable<PureAccountCategory> Query(Database db, string[] columns = null, int[] Accountid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_Account_Category (NOLOCK)");

				if (Accountid != null)
					sql.Where("AccountId IN (@0)", Accountid);

                return db.Query<PureAccountCategory>(sql);
            }
		}
		
		[TableName("dbo.Pure_AuditTrail")]
		[PrimaryKey("Id")]
		[ExplicitColumns]
		public partial class PureAuditTrail : FountainDb.Record<PureAuditTrail>  
		{
	        [Column] public int Id 
			{ 
				get { return _Id; }
				set { _Id = value; Track("Id"); }
			}
			int _Id;
			[Column("UserName")] public string Username 
			{ 
				get { return _Username; }
				set { _Username = value; Track("UserName"); }
			}
			string _Username;
			[Column("UserActivity")] public string Useractivity 
			{ 
				get { return _Useractivity; }
				set { _Useractivity = value; Track("UserActivity"); }
			}
			string _Useractivity;
	        [Column] public string Comment 
			{ 
				get { return _Comment; }
				set { _Comment = value; Track("Comment"); }
			}
			string _Comment;
			[Column("DateLog")] public DateTime? Datelog 
			{ 
				get { return _Datelog; }
				set { _Datelog = value; Track("DateLog"); }
			}
			DateTime? _Datelog;
			[Column("SystemName")] public string Systemname 
			{ 
				get { return _Systemname; }
				set { _Systemname = value; Track("SystemName"); }
			}
			string _Systemname;
			[Column("SystemIP")] public string Systemip 
			{ 
				get { return _Systemip; }
				set { _Systemip = value; Track("SystemIP"); }
			}
			string _Systemip;
		
			public static IEnumerable<PureAuditTrail> Query(Database db, string[] columns = null, int[] Id = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_AuditTrail (NOLOCK)");

				if (Id != null)
					sql.Where("Id IN (@0)", Id);

                return db.Query<PureAuditTrail>(sql);
            }
		}
		
		[TableName("dbo.Pure_User")]
		[PrimaryKey("UserId")]
		[ExplicitColumns]
		public partial class PureUser : FountainDb.Record<PureUser>  
		{
			[Column("UserId")] public int Userid 
			{ 
				get { return _Userid; }
				set { _Userid = value; Track("UserId"); }
			}
			int _Userid;
			[Column("FirstName")] public string Firstname 
			{ 
				get { return _Firstname; }
				set { _Firstname = value; Track("FirstName"); }
			}
			string _Firstname;
			[Column("MiddleName")] public string Middlename 
			{ 
				get { return _Middlename; }
				set { _Middlename = value; Track("MiddleName"); }
			}
			string _Middlename;
			[Column("LastName")] public string Lastname 
			{ 
				get { return _Lastname; }
				set { _Lastname = value; Track("LastName"); }
			}
			string _Lastname;
			[Column("UserName")] public string Username 
			{ 
				get { return _Username; }
				set { _Username = value; Track("UserName"); }
			}
			string _Username;
			[Column("UserEmail")] public string Useremail 
			{ 
				get { return _Useremail; }
				set { _Useremail = value; Track("UserEmail"); }
			}
			string _Useremail;
			[Column("UserPWD")] public string Userpwd 
			{ 
				get { return _Userpwd; }
				set { _Userpwd = value; Track("UserPWD"); }
			}
			string _Userpwd;
			[Column("PhoneNos")] public string Phonenos 
			{ 
				get { return _Phonenos; }
				set { _Phonenos = value; Track("PhoneNos"); }
			}
			string _Phonenos;
			[Column("RoleId")] public int? Roleid 
			{ 
				get { return _Roleid; }
				set { _Roleid = value; Track("RoleId"); }
			}
			int? _Roleid;
			[Column("UserImg")] public string Userimg 
			{ 
				get { return _Userimg; }
				set { _Userimg = value; Track("UserImg"); }
			}
			string _Userimg;
			[Column("UserStatus")] public bool? Userstatus 
			{ 
				get { return _Userstatus; }
				set { _Userstatus = value; Track("UserStatus"); }
			}
			bool? _Userstatus;
			[Column("CreatedBy")] public string Createdby 
			{ 
				get { return _Createdby; }
				set { _Createdby = value; Track("CreatedBy"); }
			}
			string _Createdby;
			[Column("CreatedOn")] public DateTime? Createdon 
			{ 
				get { return _Createdon; }
				set { _Createdon = value; Track("CreatedOn"); }
			}
			DateTime? _Createdon;
			[Column("ModifiedBy")] public string Modifiedby 
			{ 
				get { return _Modifiedby; }
				set { _Modifiedby = value; Track("ModifiedBy"); }
			}
			string _Modifiedby;
			[Column("ModifiedOn")] public DateTime? Modifiedon 
			{ 
				get { return _Modifiedon; }
				set { _Modifiedon = value; Track("ModifiedOn"); }
			}
			DateTime? _Modifiedon;
		
			public static IEnumerable<PureUser> Query(Database db, string[] columns = null, int[] Userid = null)
            {
                var sql = new Sql();

                if (columns != null)
                    sql.Select(columns);

                sql.From("dbo.Pure_User (NOLOCK)");

				if (Userid != null)
					sql.Where("UserId IN (@0)", Userid);

                return db.Query<PureUser>(sql);
            }
		}
}
